parameters:
  - name: environment
    type: string
  - name: serviceConnection
    type: string
  - name: resourceGroup
    type: string
  - name: location
    type: string
  - name: subscription
    type: string
  - name: module
    type: string
  - name: project
    type: string

jobs:
  - deployment: ${{parameters.project}}_env_deployment
    displayName: "${{parameters.project}} Environment Deployment"
    environment: ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzurePowerShell@5
              name: ValidateDeployment
              displayName: Validate deployment
              inputs:
                azureSubscription: ${{parameters.serviceConnection}}
                azurePowerShellVersion: LatestVersion
                ScriptType: 'InlineScript'
                Inline: |
                  New-AzResourceGroupDeployment -ResourceGroupName dmw2dihtcorg01-learning -TemplateFile deployment/modules/${{parameters.module}}/${{parameters.module}}.bicep -TemplateParameterFile deployment/modules/${{parameters.module}}/parameters/parameters.${{parameters.environment}}.json -WhatIf