# Pipeline that deploys the Databricks infrastructure. 

trigger:
- none

variables:
- template: ../configurations/configuration.variables.yml
- template: ../configurations/prjRca/configuration-infra-DEV.variables.yml # DEV as default env

pool:
  vmImage: $(VM_VERSION)

stages:

####################
##  BUILD INFRA  ##
####################

# Lint the Bicep file
- stage: buildinfra
  displayName: 'Build Environment'
  jobs: 
  - template: templates/run-code-lint.template.yml
    parameters:
      module: 'prj'

######################
##  VALIDATE INFRA  ##
######################

# Validate the bicep deployment
#- stage: validateinfra_dev
#  displayName: 'Validate Dev deployment'
#  dependsOn: buildinfra
#  variables:
#  - template: ../configurations/prjtco/configuration-infra-DEV.variables.yml
#  jobs:
#  - template: templates/whatif.yml
#    environment: TCO-IAC-DEV
#      serviceConnection: $(SERVICECONNECTION_RG)
#      resourceGroup: $(RESOURCE_GROUP)
#      location: $(LOCATION)
#      subscription: $(SUBSCRIPTIONID)
#      module: 'prj'
#      project: 'TCO'

# Validate the bicep deployment
- stage: validateinfra_dev
  displayName: 'Validate Dev deployment'
  dependsOn: buildinfra
  variables:
  - template: ../configurations/prjtco/configuration-infra-DEV.variables.yml
  jobs:
  - job: manual_approval
    pool: server
    displayName: "Manual Approval"
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 60
        inputs:
          notifyUsers: |
            prashant.101386@gmail.com
          instructions: "Hi, please validate"

####################
##  DEPLOY INFRA  ##
####################

# Deploy DEV Environment
- stage: deployinfra_dev
  displayName: 'Deploy DEV Environment'
  dependsOn: buildinfra
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
  - template: ../configurations/prjtco/configuration-infra-DEV.variables.yml
  jobs:
  - template: templates/deploy-env-infra.template.yml
    parameters:
      environment: TCO-IAC-DEV
      serviceConnection: $(SERVICECONNECTION_RG)
      resourceGroup: $(RESOURCE_GROUP)
      location: $(LOCATION)
      subscription: $(SUBSCRIPTIONID)
      module: 'prj'
      project: 'TCO'