# Pipeline that destroys TCO resource group and all its resources.

trigger:
- none

variables:
- template: ../configurations/configuration.variables.yml
- template: ../configurations/prjtco/configuration-infra-DEV.variables.yml # DEV as default env

pool:
  vmImage: $(VM_VERSION)

stages:

# Lint the Bicep file
- stage: buildinfra
  displayName: 'Build Environment'
  jobs: 
  - template: templates/run-code-lint.template.yml
    parameters:
      module: 'prj'
# Destroy DEV Environment
- stage: destroyinfra_dev
  displayName: 'Delete DEV Environment'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
  - template: ../configurations/prjtco/configuration-infra-DEV.variables.yml
  jobs:
  - template: templates/delete-env-infra.template.yml
    parameters:
      environment: TCO-IAC-DEV
      serviceConnection: $(SERVICECONNECTION_RG)
      resourceGroup: $(RESOURCE_GROUP)
      location: $(LOCATION)
      subscription: $(SUBSCRIPTIONID)
      module: 'prj'
      project: 'TCO'